# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53823a7e6aba8c8cbcefc7ac83fa16bdd6037df084f04899b69868f94e2dba7dd690fb316844c953397353d5d4ddb37a50fb806d26477b488aac99cb8be54f3b

test:
  secret_key_base: 465101df50720efb30d9f4d94099aa45dfb8a48a73ca09dbe9d4cedf3be06c87df773e2682b7b38cef402e683de22f5306a28c8447c84038c6b92bdbce9cca84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
